### ISSUE TITLE
New Dockefile breaks dockerhub building specific branches

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-ul#317]
Recently (PR https://github.com/telefonicaid/iotagent-ul/pull/310) we did some changes in the way we deal with Dockerfile

* It was moved to docker/ directory
* We get code to be build by direct download (through wget) instead of using COPY to get the code in the repo (in part because the directory move precludes the usage of COPY)

This impose a limitation in dockerhub. Up to that PR if we want to build a image based in a particular branch it is a matter of configuring that branch in docker have and trigger the build. For instance:

![imagen](https://user-images.githubusercontent.com/1534240/49867121-cbabe100-fe09-11e8-891d-2eb203d7696c.png)

With the current approach that doesn't work and we always get the code form master being built.

Maybe is a matter of injecting the proper `--build-arg` in dockerhub configuration, but I have been unable to find a suitable solution. @jason-fox what do you think?

**Comment by jason-fox** [comment]
Yes this is a **Docker Hub** Automated Build limitation of trying to produce automated Documentation for user using the same mechanism as creating an automated branch build for testing.

What I think you're actually after is the `SOURCE_BRANCH` **Env** variable which is currently only available in **Docker Cloud.**

The current approach defaults to latest `master` because that is the **branch**  hard-coded in the Dockerfile
https://github.com/telefonicaid/iotagent-ul/blob/770f3a2a77e652e51b1cf275ed97d581d92d9c9b/docker/Dockerfile#L53-L55 

You have several options here:

1) Within the `Dockerfile` line 55 replace `master` with a specific hash
* https://github.com/telefonicaid/iotagent-ul/archive/2120915c9be82fa8fcee55c2d824a39e9a082c4a.zip

2) Within the `Dockerfile` line 55 replace `master` with the name of the branch you are using:
* https://github.com/telefonicaid/iotagent-ul/archive/task/keyrockOauth2Integration-prelanding.zip

3) Build locally using a copied `Dockerfile` and replace the `RUN` statement with a `COPY`

**Comment by jason-fox** [comment]
It looks like there could be a fix soon on the Docker Hub side:

* [Introducing the new Docker Hub](https://blog.docker.com/2018/12/the-new-docker-hub/)

**Comment by fgalan** [comment]
Based on the result at https://github.com/telefonicaid/iotagent-ul/pull/346#issuecomment-478957560, this issue can be closed.
