### ISSUE TITLE
Cannot publish a new measurement to a device

### ISSUE THREAD

**Issue by jmezzera** [telefonicaid/iotagent-ul#355]
Issue described in the following stackoverflow question:
https://stackoverflow.com/questions/56367445/whats-the-right-way-to-create-a-mosquitto-subscription-with-a-device-and-iotage

**Comment by fgalan** [comment]
Let's continue the discussion in SOF and close this issue.

**Comment by jmezzera** [comment]
The issue was resolved in the SOF discussion. Thanks, btw. However, I was following the tutorial and using the requests available here:
https://github.com/FIWARE/tutorials.IoT-over-MQTT

Maybe those should be fixed?

**Comment by fgalan** [comment]
Maybe it's a good idea although it should be decided by the people in charge of tutorials (I think is @jason-fox )

**Comment by jason-fox** [comment]
> For the Ultralight IoT agent, in the previous release 1.7 if an MQTT measure arrived , when the flow of the code looked for a service group resource was ignored. Therefore the tutorial (setting the resource to blank) was fine when run against 1.7. The behaviour of the iot agent has changed for current release 1.8 and I can't see where the change has been documented, so maybe this is unexpected behaviour.

> Either way it is fair to say that the current tutorial doesn't work with the current IoT Agent and one of them (or both) needs to be fixed.


Related: 

- telefonicaid/iotagent-ul#320 - the original thread
- https://github.com/FIWARE/tutorials.IoT-over-MQTT/issues/8  - This explains the reason for the inconsistency.
- https://github.com/telefonicaid/iotagent-node-lib/pull/773 - a partial fix.

I raised this inconsistency (with at least a partial analysis on the problem) on the original thread back in **April**:  https://github.com/telefonicaid/iotagent-ul/issues/320#issuecomment-482008707

I am still awaiting advice on how to proceed. The tutorial and the code base must align and the loophole in the code base should be closed. The question remains how to do this.

**Comment by fgalan** [comment]
Yes, this has been around for a while, since April, and we know the couple of PRs that are on the table related to this (https://github.com/telefonicaid/iotagent-node-lib/pull/773 and https://github.com/telefonicaid/iotagent-ul/pull/347). Thanks for them!

Unfortunatelly, although @mrutid provided some early feedback, we haven't been able yet review in deep due to other priorities. We need to think about the "final picture" of the resource thing and its relationship with the transports and how the fix you has proposed fits in this final picture, taking also into account of course backward compatibility aspects.

Due to this may take a while (holiday season doesn't help :) I'd suggest to align the tutorial with the configuration that works (i.e. the one with `"/iot/d"` instead of `""`) and a disclaimer explaining the situation and that it will eventually changed. You can even provide links to the main issue and PRs where discussion is taking place.

Thanks again and sorry fot the inconveniences!
